class DatabaseBackend:
    def create_table(self, model): ...

    def insert(self, model): ...

    def update(self, model): ...

    def delete(self, model): ...

    def select(self, model, **filters): ...
